### PR TITLE
Whatsapp: Update waVersion to version 2.2033.7 and Deprecated clientVersion 

### PR DESCRIPTION
**Pull request by beshoo**
https://user-images.githubusercontent.com/4635115/89966167-30f74b80-dc57-11ea-9e31-517e7dace0da.png
Whatsapp chrome update waVersion  and i can not see the anything about the clientVirsion in the chorme!

### CODE REVIEW

**Comment by beshoo** [comment]
Client has version 0.4.2080
Server has version 2.2033.7
New major detected 2

**Comment by beshoo** [comment]
Hello @SchulteMK 
Kindly can you merge this PL! since it is very important

**Comment by tulir** [comment]
Your screenshot clearly shows three fields: `Windows`, `Chrome` and `7`. The last field is what go-whatsapp calls clientVersion. The name is probably inaccurate, but the field is definitely there.

You didn't even actually remove the clientVersion field, you just removed the ability to set it, which means the default value (`0.1.0`) is always sent.

My browser sends `Linux`, `Firefox` and `x86_64`. I think we should re-add the third parameter in `SetClientName` and rename `longClientName`->`osName`, `shortClientName`->`clientName` and `clientVersion`->`osVersion`

**Comment by beshoo** [comment]
So what is the client virsion i can not find it in anu please in the chrome
soket...

Please confirm

**Comment by beshoo** [comment]
So you mean the client virsion is 7?

**Comment by beshoo** [comment]
@SchulteMK what do think?

**Comment by tulir** [comment]
> So you mean the client virsion is 7?

Yes, which is why I'm assuming the field is actually the OS version rather than client version.

`longClientName` / `osName` is the text shown in the app.
`shortClientName` / `clientName` is what determines the icon shown in the app (known icons: `Chrome`, `Firefox`, `Safari`, `IE`, `Edge`, `Opera`).
`clientVersion` / `osVersion` doesn't seem to be shown in the app, but needs to be sent during login anyway

**Comment by beshoo** [comment]
> > So you mean the client virsion is 7?
> 
> Yes, which is why I'm assuming the field is actually the OS version rather than client version.
> 
> `longClientName` / `osName` is the text shown in the app.
> `shortClientName` / `clientName` is what determines the icon shown in the app (known icons: `Chrome`, `Firefox`, `Safari`, `IE`, `Edge`, `Opera` - unrecognized names make it show a generic icon).
> `clientVersion` / `osVersion` doesn't seem to be shown in the app, but needs to be sent during login anyway

Thank you very much for this and I talked back the update and add the new version of the waVersion = []int{2, 2035, 14}
Well, we all do mistakes :) sorry!

**Pull request merged**
