### PR TITLE
Move examples to seperate repository & other cleanup

### PR DESCRIPTION
**Pull request by SchulteMK**
Moving examples to remove dependencies from the main package and to reduce the overall size.

### CODE REVIEW

**Comment by SchulteMK** [comment]
@beshoo What do you think about my PR?
I am trying to clean up the code in general to be more complient with the go spec and recommendations. I am currently reworking the errors used in this package, to use the new errors from the standard library.

**Comment by beshoo** [comment]
Well, l am not sure if this will break anything. Our api is working just fine. Will this move will break anything?

Moreover, this lib is an academic lib, users expect to find examples omce they download it to there machines. 

I am ok with extra space, rather than telling the user, oh you need example, pleas head to this link. 

Think for the big picture, we are looking for the easiest way user can join and run the example ASAP. 

Thanks for your mention. 
What do you think? 

Regard

**Comment by SchulteMK** [comment]
Yes I totally agree that it is an academic lib. At the current moment the project is almost completely stopped improving since we finished our academic project. 
On the one hand it is okay as it is, but on the other hand I am debating if I want to continue the project and fix the issues and improve it or if I want to leave it as it is and only merge a PR here and there. 
To be a real API, which is up to the standard of most APIs, many parts of the project need to be redesigned.

**Comment by beshoo** [comment]
Well, as long as you will not break any functions or redesigned how we have to use, **backward compatibility**

As examples, if someone hired a freelanceer to creat an api for him, this end user use to update the lib and expect to have everything is working just fine. 

So if the work you are going to add will only focus on the internal functions it will be welcome.

But if you will break the backwards compatibility, then this will be a big problem and you have to take care of this issue

**Comment by beshoo** [comment]
@SchulteMK 
With a small search on GitHub, you will find a lot of users who already using this piece of art and building around it.

I respect each one of them, all of them expect a robust lib, all of them created a wonderful projects using this lib. so we have to keep the interface intact.

That is what I am looking for.

**Comment by beshoo** [comment]
@SchulteMK Do you agree with me, that we have to keep back compatibility?
So old user will not face problems with the api.

**Pull request closed without merging**
