### PR TITLE
Added support for receiving Stickers and updated proto

### PR DESCRIPTION
**Pull request by sthales**

### CODE REVIEW

**Comment by tulir** [comment]
@sthales Where did you get the updated protobuf definitions from? It seems to differ from the ones that my fixed protobuf extractor (https://github.com/sigalor/whatsapp-web-reveng/pull/220) gets from web.whatsapp.com.

**Comment by sthales** [comment]
@tulir I've got it from [/sigalor/whatsapp-web-reveng/blob/master/doc/spec/def.proto](/sigalor/whatsapp-web-reveng/blob/master/doc/spec/def.proto)

**Comment by Ased2235** [comment]
is it working? cuz i tried like this & it's not working
```
func (wh *waHandler) StickerMessageHandler( message whatsapp.StickerMessage) {
	

	fmt.Println("StickerMessage: ", message)
}
```

**Comment by sthales** [comment]
> is it working? cuz i tried like this & it's not working
> 
> ```
> func (wh *waHandler) StickerMessageHandler( message whatsapp.StickerMessage) {
> 	
> 
> 	fmt.Println("StickerMessage: ", message)
> }
> ```

Yes, it is.
Try `"HandleStickerMessage"`

```
func (wh *waHandler) HandleStickerMessage( message whatsapp.StickerMessage) {
	
	fmt.Println("StickerMessage: ", message)
}
```

**Comment by Ased2235** [comment]
> > is it working? cuz i tried like this & it's not working
> > ```
> > func (wh *waHandler) StickerMessageHandler( message whatsapp.StickerMessage) {
> > 	
> > 
> > 	fmt.Println("StickerMessage: ", message)
> > }
> > ```
> 
> Yes, it is.
> Try `"HandleStickerMessage"`
> 
> ```
> func (wh *waHandler) HandleStickerMessage( message whatsapp.StickerMessage) {
> 	
> 	fmt.Println("StickerMessage: ", message)
> }
> ```

Oh It's working, Thanks. BTW is there anyway we can send stickers?

**Pull request merged**
