### PR TITLE
Add Block/Unblock Contact Function

### PR DESCRIPTION
**Pull request by jeremia49**
as the title said

### CODE REVIEW

**Comment by jeremia49** [comment]
Let me know what you think 😄

**Comment by rhsobr** [comment]
i really suggest something like that:

```
func (wac *Conn) BlockContact(jid string) (<-chan string, error) {
   return wac.handleBlockContact("add", jid)
}

func (wac *Conn) UnblockContact(jid string) (<-chan string, error) {
   return wac.handleBlockContact("remove", jid)
}

func (wac *Conn) handleBlockContact(action, jid string) (<-chan string, error) {
	ts := time.Now().Unix()
	tag := fmt.Sprintf("%d.--%d", ts, wac.msgCount)

	netsplit := strings.Split(jid, "@")
	cusjid := netsplit[0] + "@c.us"

	n := binary.Node{
		Description: "action",
		Attributes: map[string]string{
			"type":  "set",
			"epoch": strconv.Itoa(wac.msgCount),
		},
		Content: []interface{}{
			binary.Node{
				Description: "block",
				Attributes: map[string]string{
					"type": action,
				},
				Content: []binary.Node{
					{
						Description: "user",
						Attributes: map[string]string{
							"jid": cusjid,
						},
						Content: nil,
					},
				},
			},
		},
	}

	return wac.writeBinary(n, contact, ignore, tag)
}

**Comment by jeremia49** [comment]
Hi there, thanks for your suggestion , I will refactor my code.

Pada tanggal Jum, 18 Des 2020 pukul 00.53 Rafael Henrique <
notifications@github.com> menulis:

**Comment by jeremia49** [comment]
Done 😃

**Comment by beshoo** [comment]
I like this PL, but we need to get more approval from the community, I don't have time to test it, but it seems fine for me. 
Let's wait and see who thumps up will be.

Happy Christmases

**Comment by jeremia49** [comment]
Ok, thanks 😊

Merry Christmas

**Comment by DonovanDiamond** [comment]
I think this is great!

**Review by DonovanDiamond — APPROVED** [review]

**Review by Diden05 — APPROVED** [review]

**Comment by beshoo** [comment]
I still have no time to test this PL. @DonovanDiamond @Diden05 did you test it?

**Comment by jeremia49** [comment]
I have test it several times and it's working

**Review by SchulteMK — APPROVED** [review]

**Pull request merged**
