### PR TITLE
Fix/buffersize Causing high memory usage

### PR DESCRIPTION
**Pull request by x00b**
Websocket buffer size was causing high memory usage during ws conn, issues tracking:

Suggest in #282 , discussion in #328  and benchmark/testing in #350 

ps: re-opening pr

### CODE REVIEW

**Comment by beshoo** [comment]
@x00b 
I note that the total allocate memory is growing but slowly....
Is that can be managed by **GOGC**?

Have a look 
There is 2 session hooked to the api. 

I Started with : 
**Alloc = 3 MiB TotalAlloc = 21 MiB Sys = 15 MiB NumGC = 10** 
After 7 hours 
 **Alloc = 5 MiB TotalAlloc = 35 MiB Sys = 17 MiB NumGC = 205**

What do you think? 
But keep in mind that without this update l guarantee more than 7 restarts for the api.

**Comment by x00b** [comment]
The default GC behavior can cause this unnecessary spikes, i think it might be related to https://github.com/golang/go/issues/14812 and maybe https://blog.twitch.tv/en/2019/04/10/go-memory-ballast-how-i-learnt-to-stop-worrying-and-love-the-heap-26c2462549a2/ too. 

I know that this PR really fix the high memory usage but the GC might be necessary to control directly in the application. But lets keep investigating it.

**Comment by beshoo** [comment]
Do you have any idea or method of controlling GC in the application?

**Comment by gabstv** [comment]
I went to `gorilla/websocket` to check what goes when the size is set to zero:
```go
const (
    defaultReadBufferSize  = 4096
    defaultWriteBufferSize = 4096
)
```

**Comment by beshoo** [comment]
@gabstv Than you for your reply, I am not sure I followed you correctly.
We already changed these values to zero in order to limit down the high memory usage!

So what is the purpose of adding 4096 value?

**Comment by x00b** [comment]
When we set buffer size to zero gorilla/websocket change it to 4096, that's what he said.

But the default value is working fine. There's no need to increase it like it was and i think not even changing this PR to use other value instead of zero(so websocket doesn't set a higher default size) value)

**Comment by beshoo** [comment]
Today I decide to make a very ruff test.
I sent more than 10000 requests to the QR loader within 1 min.
API did not go down at all, but I note if I run the QR and check for the profile I will get this memory trace:

```
INFO[1176] Url /api/profile/me
Alloc = 1041 MiB        TotalAlloc = 4956 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1177] Url /api/profile/me
Alloc = 1042 MiB        TotalAlloc = 4957 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1178] Url /api/profile/me
Alloc = 1043 MiB        TotalAlloc = 4959 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1178] Url /api/profile/me
Alloc = 1044 MiB        TotalAlloc = 4960 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1179] Url /api/profile/me
Alloc = 1045 MiB        TotalAlloc = 4961 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1180] Url /api/profile/me
Alloc = 1047 MiB        TotalAlloc = 4962 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1181] Url /api/profile/me
Alloc = 1048 MiB        TotalAlloc = 4963 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1181] Url /api/profile/me
Alloc = 1049 MiB        TotalAlloc = 4964 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1182] Url /api/profile/me
Alloc = 1050 MiB        TotalAlloc = 4966 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1183] Url /api/profile/me
Alloc = 1051 MiB        TotalAlloc = 4967 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1184] Url /api/profile/me
Alloc = 1053 MiB        TotalAlloc = 4968 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1184] Url /api/profile/me
Alloc = 1054 MiB        TotalAlloc = 4969 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1185] Url /api/profile/me
Alloc = 1055 MiB        TotalAlloc = 4970 MiB   Sys = 1860 MiB  NumGC = 41
INFO[1186] Url /api/profile/me
Alloc = 1056 MiB        TotalAlloc = 4972 MiB   Sys = 1860 MiB  NumGC = 41

```
Note that each request will cost 1 MB! is that reasonable? 
Overall, my server has 128 GB of ram.

Have look to the top



` 
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
5769 root      20   0 2072048   1.8g   7924 R  21.5  1.4  12:41.30 wa-api
`
it is using 21% of the CPU - I have 24 core.
But ram 1.4
I am not sure if this is an accurate way to test

But I believe we have to utilize GC somehow in the base lib.
PS: While testing I note this message jump a lot 
`ERRO[1752] ErrConnectionFailed connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF
` Any idea what is going on here?

**Comment by x00b** [comment]
Are you disconnecting/deleting the Wac after Qrcode timeout? About the ErrConnectionFailed... Try implementing the HandlerError logic, if you search the issues here you see that this Err is handled pretty well with handler error

About the base lib implementing a GC call by default doesn't matter until we find exactly where those bugs are.

I am having whatsapp conn issues too. But don't think might be related to this PR but with latest whatsapp web updates(which by the way is going to add new features).

**Comment by beshoo** [comment]
I am not aware how do delete the wac after the timeout

Here is my qr function 
```

func ScanQr(params profile.ScanQrParams) middleware.Responder {                 
        qr := make(chan string)                                                 
        errCh := make(chan error)                                               
                                                                                
        go func() {                                                             
                sessionID := params.SessionID.String()                          
                handler, err := wa.Login(qr, params.ProxyURL, sessionID)        
                if err != nil {                                                 
                        errCh <- err                                            
                }                                                               
                wa.Connections[sessionID] = handler                             
        }()                                                                     
                                                                                
        select {                                                                
        case err := <-errCh:                                                    
                errText := err.Error()                                          
                return profile.NewScanQrDefault(500).WithPayload(&models.Error{ 
                        Code:    500,                                           
                        Message: &errText,                                      
                })                                                              
        case qrText := <-qr:                                                    
                return profile.NewScanQrOK().WithPayload(&models.QRCode{        
                        Base64: qrText,                                         
                })                                                              
                                                                                
        }                                                                       
                                                                                
}
```

And here is wac creater


```
func Login(qr chan string, proxyURL *strfmt.URI, sessionID string) (*WaHandler, error) {

var proxyURLString *string
if proxyURL != nil {
temp := proxyURL.String()
proxyURLString = &temp
}

var wac, err = NewConn(proxyURLString)
if err != nil {
return nil, err
}
wac.SetClientName(longName, shortName )
wh := WaHandler{
Wac:             wac,
lastMessageTime: uint64(time.Now().Unix()),
SessionID:       &sessionID,
State:           RESUME,
Signal:          make(chan Signal),
Queue:           make(chan func() error),
ChBrodcastQuit:  make(map[string]chan struct{}),
OnlineNumbers:   make(map[string]OnlineStatus),
}
wac.AddHandler(&wh)
session, err := wac.Login(qr)
if err != nil {
return nil, err
}
err = storage.CreateSession(WASessionFromSession(sessionID, proxyURLString, nil, session))
if err != nil {
log.Errorf("Session Storing failed %v", err)
return nil, err
}
wh.ProcessQue()
return &wh, nil
} 
```

Please advise me how to implement the timeout? 

Yes i am handling the error. 

Regarding WhatsApp updates, will it break what we allready have? 
Please share more details.... 

Regard

**Comment by beshoo** [comment]
@x00b 
Have a look with me, after 8 days with one session I have this status

`Alloc = 19 MiB  TotalAlloc = 203 MiB    Sys = 36 MiB    NumGC = 5316
`
Note the **NumGC** , what do you think is it normal?

**Comment by x00b** [comment]
It might be something in your code i think. Probably an infinite for {} loop that is running in a goroutine or something like that that is causing a high memory usage and the garbage collector cannot work properly(clean the not-used memory).

If you have an infinite for loop, it might be the cause... Never do infinite for{} loop in Go

**Pull request merged**
