### PR TITLE
add feature to mention / tag people

### PR DESCRIPTION
**Pull request by jeremia49**
add feature to mention / tag people

### CODE REVIEW

**Comment by beshoo** [comment]
How to use it?

**Comment by jeremia49** [comment]
Example to mention / tag people in group  : 

ContextInfo := whatsapp.ContextInfo{
MentionedJid:    []string{"phone_number@s.whatsapp.net"}, // make sure you also fill same number on text message
 } 

msg := whatsapp.TextMessage{
Info: whatsapp.MessageInfo{
RemoteJid: message.Info.RemoteJid,
},
ContextInfo: ContextInfo,
Text:        "@phonenumber ",   // make sure that you use same number in MentionedJid
}
 wh.wac.Send(msg)

**Comment by beshoo** [comment]
I have a great idea you may implement it,
Why dont you parce the text find 
Any @123456789
Which mean user want to tag this number, numbers and you add them to the context? 
So user will only send normal text messages with @123456

**Comment by beshoo** [comment]
I believe this has to be add to send func

**Comment by jeremia49** [comment]
yeah, I think so.

**Comment by Ased2235** [comment]
thanks, can you take a look at this too? #385

**Comment by beshoo** [comment]
@jeremia49 Are you going to implement the idea that I propose to you?

**Comment by Valdenirmezadri** [comment]
that would be great

**Comment by jeremia49** [comment]
I think it would be ok if I split all the spaces, then use regex to validate phone number , to differentiate "@" between email and phone number .  How do you think ? @beshoo 

Do you agree with me ? or any idea ?

**Comment by jeremia49** [comment]
mentionedArr := []string{} //array mentioned phone number
	text := "Hi There \n @113526146143 @01987654321" //simulate text message
	splittext := strings.Split(text, " ")
	re := regexp.MustCompile(\`^@(\d+)$\`)
	for _, t := range splittext {
		if re.MatchString(t) {
			mentionedArr = append(mentionedArr, t)
		}
	}
	fmt.Println(mentionedArr)

**I'm going to implement this code, but as you see, i split every spaces then test it one by one with regex, I think this code will lower the perfomace , is it okay ?** 
**Btw, notice that if I make something like "@3145144361\n" then this code will not work. because "\n" make the regex return false. Any ideas ?**

**Comment by beshoo** [comment]
I believe it is fine, but why do you want to explode space, why dont you
apply this type of regex

/@[1-9]{7,17}/img

This will give you an array of the available numbers in the string which
start with @ and the number length between 7 and 17
Then you loop over the array to add the numbers to the message?

**Comment by jeremia49** [comment]
Thank you for your help.
Btw, I think the regex range should start from 0-9, not 1-9, e.g.
6289509.... will not work because the range start from 1.

Pada tanggal Jum, 3 Jul 2020 pukul 08.48 beshoo <notifications@github.com>
menulis:

> I believe it is fine, but why do you want to explode space, why dont you
> apply this type of regex
>
> /@[1-9]{7,17}/img
>
> This will give you an array of the available numbers in the string which
> start with @ and the number length between 7 and 17
> Then you loop over the array to add the numbers to the message?
>
>
>
>
>
>
>

**Comment by beshoo** [comment]
Yes that correct 😅 it is typo mistake

**Comment by jeremia49** [comment]
For anyone needs to mention phone number can check this [Golang Playground](https://play.golang.org/p/MqMfu81XQKi) 

I am afraid I can't implement that feature to the message.go in the send Function.  I don't understand the proto message 😅 . The easiest way to implement that feature maybe to modify the getContextInfoProto. I'm still working on that.

**Comment by jeremia49** [comment]
@beshoo @sthales How do you think about my recent commit ? Review my code, please 😅

**Comment by jeremia49** [comment]
Review my commit please

**Comment by beshoo** [comment]
@jeremia49  woo, a lot of modifications
I believe i can not approve this commit my self since it is updating a fundamental part, and we need to have a full review from the communitie.

But a question, what if user tag a wrong number. 
What will happened? 

What uf he tag hem self in a private chat? 
Tag in a private chat a wrong number... Etc

**Comment by sthales** [comment]
It needs a lot of validations, like @beshoo said. We need to check if the number exist and if it uses WhatsApp, if it's not a private chat, if the user you are mentioning is in the group...

**Comment by beshoo** [comment]
@jeremia49 and as long as this not that very important add on, I believe you have to provide full test, so we can review base on your test, then we may approve the commit.

Please do full test on your commit, l can not see good logging method to the console 
You need to check the number if it is available in the chat... 
You need only tag in group since it is the only place we can tag in... 
You need to prevent user to tag him self... 
See, a lot of modifications, even after all these updates, we need to valid the updates.. 
What if i tag with a photo caption... Is it support images? 

As i said before, you are touching a very sensitive part of the library.

**Comment by jeremia49** [comment]
Thank you  @beshoo @sthales ,  

I'm going to optimize and test this feature. 
I will close this PR and make the new one.
Once again, Thank you guys 😄

**Comment by arisawali2014** [comment]
gambar
why do i get this error?

**Comment by jeremia49** [comment]
> 
> 
> gambar
> why do i get this error?

You should modify message.go, so whatsapp.ContextInfo have the MentionedJid field. In case if you don't know how to modify that, you can follow [my first commit](https://github.com/Rhymen/go-whatsapp/pull/401/commits/00a1a1bca0314866636c296d15455fe08e0a6c46) .

**Comment by skius** [comment]
Has there been any progress on this? Personally, I think this feature was just fine as it was in the first commit. Other features in this library (e.g. quoting messages using QuotedMessage + QuotedMessageID + Participant) also don't have any validation implemented as far as I can tell.

**Comment by Ased2235** [comment]
> Has there been any progress on this? Personally, I think this feature was just fine as it was in the first commit. Other features in this library (e.g. quoting messages using QuotedMessage + QuotedMessageID + Participant) also don't have any validation implemented as far as I can tell.

Hey, as far as I remember, this feature was already implemented in this library?

**Comment by Ased2235** [comment]
Of there's any important features are missing i say those are
Clear chat
Accept group invites 
As it stands, i tried both. In clear chat msg, i git error 402 while i didn't received any error in accept group invites but it is crashing whatsapp on my phone but idk why tho. If you have any idea it would be great to hear them.

**Comment by skius** [comment]
> 
> 
> > Has there been any progress on this? Personally, I think this feature was just fine as it was in the first commit. Other features in this library (e.g. quoting messages using QuotedMessage + QuotedMessageID + Participant) also don't have any validation implemented as far as I can tell.
> 
> Hey, as far as I remember, this feature was already implemented in this library?

Could you point me to an example? This PR wasn't merged and to utilize the described functionality I had to commit the changes to a fork.

**Comment by Ased2235** [comment]
You can check this out #217 but you might want to improve it a bit.

**Comment by skius** [comment]
@Ased2235 I'm talking about the feature described in this PR, which is about tagging/mentioning and not quoting 😄 I mentioned quoting as an example of an already implemented feature which works in a similar way to this one, also not validating the quotations, to argue that I don't see the issue with the way tagging was implemented in the first commit of this PR.

**Comment by Ased2235** [comment]
> @Ased2235 I'm talking about the feature described in this PR, which is about tagging/mentioning and not quoting 😄 I mentioned quoting as an example of an already implemented feature which works in a similar way to this one, also not validating the quotations, to argue that I don't see the issue with the way tagging was implemented in the first commit of this PR.

Oh sry about that 😅 i missed read your post. Can you take a look at my implementation requests? I talked it over with @beshoo but he doesn't seems to have any idea why it's not working

**Pull request closed without merging**
