### PR TITLE
Allowing to resuse media url

### PR DESCRIPTION
**Pull request by rohit-32**
This decouples media upload from message send function, this allows to separate upload call, and hence the caller can decide to reuse media URL for broadcast

### CODE REVIEW

**Comment by beshoo** [comment]
Please update stract to meet latest WhatsApp update 

```
type MediaConn struct {
	Status    int `json:"status"`
	MediaConn struct {
		Auth  string `json:"auth"`
		TTL   int    `json:"ttl"`
		Hosts []struct {
			Hostname string `json:"hostname"`
			IPs []interface{} `json:"ips"`
		} `json:"hosts"`
	} `json:"media_conn"`
}
 
```

**Comment by j-f-r** [comment]
The IP isn't really used right? Why does it need to be in the struct?

**Comment by beshoo** [comment]
@SchulteMK please close this, it is not valid, and the developer did not reply to the advice to fix the struct which lead to image issues.

I am  not sure if this pl is a great one, but since the developer dos not follow the recommendations, l believe we have to protect the community by closing this pl. 

Regard

**Comment by rohit-32** [comment]
@SchulteMK I think there is a mistake this pull has nothing to do with @beshoo  changes, this adds a feature which will save bandwidth while sending multiple messages with same media URL

**Pull request closed without merging**
