### PR TITLE
Implement Full Chat history, add an example

### PR DESCRIPTION
**Pull request by kaxap**
Addresses issues #50, #86, #105, #133, #173

### CODE REVIEW

**Comment by kaxap** [comment]
#173 resolved with https://github.com/Rhymen/go-whatsapp/pull/185/commits/60b6c420201bf0c04a7198b796e4e4fb05379675 and https://github.com/Rhymen/go-whatsapp/pull/185/commits/3192a0e1fc14979881c86bcc93b27fcedd47eee2

**Comment by houstondapaz** [comment]
Amazing!! Thank's a lot for that

**Comment by SchulteMK** [comment]
Thank you for your great contribution. I saw that you are working on implementing LocationMessages, I am looking forward to the result. 👍

**Comment by kaxap** [comment]
@SchulteMK @houstondapaz you're very welcome. 

> I saw that you are working on implementing LocationMessages, I am looking forward to the result. 👍
I'll create a pull request ASAP

**Pull request merged**
