### PR TITLE
incorrect method name

### PR DESCRIPTION
**Pull request by Code8525**
wrong method name, so it will be more correct!

### CODE REVIEW

**Comment by beshoo** [comment]
No, it is correct base on the GETR AND SETR rules, you have to get or set!

**Comment by Code8525** [comment]
good

**Comment by AlmogBaku** [comment]
I agree, using "get" is not go-idiomatic...

**Comment by lesmo** [comment]
Not idiomatic, but this is a breaking change.

It should be added as a separate method, and have the other one issue a warning about deprecation to give developers time to adjust.

**Comment by AlmogBaku** [comment]
@lesmo this is a new feature anyway...

**Comment by lesmo** [comment]
It's changing existing functionality, any implementor using `GetConnected()` and `GetLoggedIn()` will no longer work **without warning**. As these are _public_ methods, a refactor of this sort must be planned and communicated.

**Pull request merged**
