### PR TITLE
Fix error socket close code 1000

### PR DESCRIPTION
**Pull request by lutpiero**
Add a Client Version on Login fix the error

### CODE REVIEW

**Comment by beshoo** [comment]
@lutpiero 
Client Version:  10.15.4

**Comment by lutpiero** [comment]
You

> @lutpiero
> Client Version: 10.15.4

You can create any number,  its a client version anyway.
I've tried different version and it works.

**Comment by luwice** [comment]
Thanks Big Bro

**Comment by ferdian** [comment]
Thanks my bro

**Pull request closed without merging**
