### PR TITLE
Improved message replies 

### PR DESCRIPTION
**Pull request by sthales**

### CODE REVIEW

**Comment by Ased2235** [comment]
When can we use this update?

**Comment by codenoid** [comment]
@Ased2235 

```
mkdir -p $GOPATH/src/github.com/sthales
cd $GOPATH/src/github.com/sthales
git clone https://github.com/sthales/go-whatsapp -b improved-reply-message
```

**Comment by Ased2235** [comment]
@codenoid awesome works!! it's works on pm & groups too. BTW is it possible to mention someone in group too? like asked in #162  i have an idea how it's can be done but haven't worked out

**Comment by sthales** [comment]
> BTW is it possible to mention someone in group too? like asked in #162 i have an idea how it's can be done but haven't worked out

Not yet. I'm planning to work on this in the future...

**Comment by Ased2235** [comment]
> Not yet. I'm planning to work on this in the future...

Ok thanks!!

**Pull request merged**
